language: cpp

compiler: gcc
env: 
  global:
    - COMPILER=g++-4.9
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "hRnkJsIp+C0iXEdJ57iD2e7/wKRwy1tLUkgVjl1eFUvcuYSewX2vieGPzHS/AMB8jFaLm9vSRUN3RNV5wqZPX2GuWEwecHT2pLukSRxgxPYCrgC41hi16rswNw8Rlz33Yo7neDOeS+7rUgG4WLkH2zeFwOrYVOkIO0kc7G36nR46SEOhIx2qxzG8jdnDd1i2Byl3NDQVlPaWYqTrbGkvn62xlcXXdv85MY5Wm2CW3J6LYLbgYJTBODgt8iUbDB+1/Ws51RrVhytamo8YeBUQFaRDEEZYuVDewuy5ti1M1qjwUlwhCJAxGhgD14ntdWq3Aw+Rgsv/io6LAccY3SDPUBL8EG5XlQIOPaCr8SLuuc47K9eS9120nD1XT2RFq3BYlAbbT8pl6udLrlh4PQjBOyEfSarkif6JVqEbCdFSbuir1F3xtKsQztMiO0v0xX/0W+ai5czJl/Q0acz7FtAQU1VLqb7KI4NkV9dCCMzrb+r4+djw+BKwlJv4pFvVrZAvzIGJneslUJqG653Qf8bxkypMUrVsqBQPD+X21Meo9AHunBpCksnQZWxiWqBV4Pi1bl031mKJ7D75dizCDSRyguiRLEMVrOcBmV+mwmc7x/2roX0fxdOad8dKA+h1q9taLc9AIj6ObDBRe9VMHb7FHuV0Lv7Zzsl3QSoeA5RjZC0="
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-4.9','valgrind']
  coverity_scan:
    project:
      name: "FragJage/xPLLib"
      description: "xPLLib library for xPL protocol"
    notification_email: inscrip.jage@free.fr
    build_command_prepend: "cov-configure --comptype g++ --compiler $COMPILER --template && cmake . -G'Unix Makefiles' -DCMAKE_CXX_COMPILER=$(which $COMPILER)"
    build_command: "make"
    branch_pattern: coverity_branch
    
install:
  - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git

script:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then cmake . -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $COMPILER); fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then make; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ./test/bin/unittest; fi

after_success:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then coveralls --include src --gcov-options '\-lp' --gcov 'gcov-4.9'; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then valgrind --error-exitcode=1 --leak-check=full ./test/bin/unittest; fi
